= Morecurves Lua API
:toc:

== Built-in Lua Functions
export_mesh("filename"[, export_normals=true])::
Exports valid minetest obj file, respecting groups (for texturing), using normals by default.

add_triangle(v1x, v1y, v1z, v2x, ...)::

TIP: This function is never meant to be hand-typed, unless you are extending functionality.

This function takes 25 numbers, in the following order:
....
Vertex 1: x, y, z
Vertex 2: x, y, z
Vertex 3: x, y, z
Vertex 1-Normal: x, y, z
Vertex 2-Normal: x, y, z
Vertex 3-Normal: x, y, z
Vertex 1-UV: x, y
Vertex 2-UV: x, y
Vertex 3-UV: x, y
Group Number
....

reset_mesh()::
Delete any previously added data to the current mesh.

== Common Shape Functions
axis_aligned_rectangular_prism(middle, dimensions, tesselated=false, g1=1, g2=2, g3=3, g4=4, g5=5, g6=6)::
tesselated = false by default - i.e. stretch the texture
g1:top, g2: bottom, g3: right, g4:left, g5:rear, g6:front

quad(v8_pos1, v8_pos2, v8pos3, group_number)::
This function will calculate normals for you, using the 3 positions and winding order, don't bother filling out the normals, they will be overwritten.

flat_shaded_quad(v5_pos1, v5_pos2, v5_pos3, v5_pos4)::
.

== Point Generation Functions
superellipse_polar_point(theta, radius, a, b, m, n)::
.
superellipse_polar_segments(starting_theta, ending_theta, precision, radius, a, b, m, n, xtra_origin_offset)::
Returns points array object of v4, with precision number of points (must be >=2).

== Points Functions

offset(points, x, y)::
.
rotation(points, theta)::
.
mirror_x(points, y_offset)::
.
mirror_y(points, x_offset)::
.

length(points)::
calculate the linear length of the provided points

== 2D Curve Functions
1curve_open(points, v2_corner, height)::
Generates a 3d curve piece using the provided 2d points array and corner point, with open sides.

1curve_closed(points1, v2_corner, height)::
Generates a 3d curve piece using the provided 2d points array and corner point, with closed sides.

2curve_open(points1, points2, height)::
Generates a 3d curve piece using the provided 2 points arrays with open sides.

2curve_closed(points1, points2, height)::
Generates a 3d curve piece using the provided 2 points arrays with closed sides.

== 3D Curve Functions